version: '3.7'

services:
  go:
    image: d-hayashi/k8s-slurm-injector:latest
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ./:/go/app
    command: air
    ports:
      - 8888:8888
      - 2345:2345
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE