apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep-less
  labels:
    k8s-slurm-injector/injection: enabled
spec:
  shareProcessNamespace: true
  containers:
    - name: busybox
      image: curlimages/curl:7.75.0
      args:
        - sleep
        - "100"
  restartPolicy: OnFailure