apiVersion: v1
kind: Pod
metadata:
  name: sample-pod-auto
  labels:
    k8s-slurm-injector/injection: enabled
    k8s-slurm-injector/node-specification-mode: auto
spec:
  containers:
    - name: busybox
      image: curlimages/curl:7.75.0
      args:
        - env
  restartPolicy: Never