apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep-less
  labels:
    k8s-slurm-injector/injection: enabled
spec:
  containers:
    - name: busybox
      image: busybox
      args:
        - sleep
        - "100"