apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample-statefulset
spec:
  serviceName: "sample-statefulset"
  replicas: 1
  selector:
    matchLabels:
      app: sample-statefulset
  template:
    metadata:
      labels:
        app: sample-statefulset
    spec:
      containers:
        - name: busybox
          image: curlimages/curl:7.75.0
          env:
            - name: K8S_SLURM_INJECTOR_INJECTION
              value: enabled
            - name: K8S_SLURM_INJECTOR_NODE_SPECIFICATION_MODE
              value: manual
            - name: K8S_SLURM_INJECTOR_PARTITION
              value: ubuntu
            - name: K8S_SLURM_INJECTOR_NODE
              value: nsx
          args:
            - sleep
            - "300"
      restartPolicy: Always